apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-harness
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: hello-harness
  template:
    metadata:
      labels:
        app: hello-harness
    spec:
      containers:
      - name: hello-harness-pod
        image: sreelk589/docker-kubernetes-hello-world:latest
        ports: 
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: hello-harness-service
spec:
  selector:
    app: hello-harness
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
